# Supports colors like &1. Full list here: https://htmlcolorcodes.com/minecraft-color-codes/
# Supports unicodes. Including custom. Write \\uXXXX and it will parse it

emojies:
  heart:
    text: "<3"
    emoji: "&c❤&r"
  flag_en:
    text: ":flag_en:"
    emoji: '\uE106'
  smile:
    text:
      - ":)"
      - ":}"
      - ":]"
    emoji: "&6☺&r"
