name: Emojies
main: com.lith.emojies.Plugin

version: 0.0.2
api-version: 1.20

description: A MineCraft plugin for emojies
author: Lith
website: https://github.com/ImLith/MC-Emojies

depend: [LithCore]
softdepend: []
