name: Emojies
main: com.lith.emojies.Plugin

version: 0.0.4
api-version: 1.20

description: A MineCraft plugin for emojies
author: Lith
website: https://github.com/ImLith/MC-Emojies

depend: [LithCore]
softdepend: []

commands:
  emojiesReload:
    description: Reload emojies configs
    usage: /<command>
    permission: emojies.reload

permissions:
  emojies.reload:
    description: Reload emojies configs
    default: op
